import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
type Memory={id:string;memory_type:string;subject_id:string|null;title:string;summary:string;state:string;data:Record<string,unknown>;occurred_at:string};
type Pattern={id:string;pattern:"recurrence"|"reopened_condition"|"repeated_evidence_change"|"repeated_ai_indicator"|"response_cycle";title:string;detail:string;confidence:"high"|"medium";memoryIds:string[];firstObserved:string;lastObserved:string;boundary:string};
const str=(v:unknown)=>typeof v==="string"&&v?v:null;
export async function GET(){
try{
const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser();
if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});
const {data:profile}=await supabase.from("profiles").select("organization_id").eq("id",user.id).maybeSingle();
if(!profile?.organization_id)return NextResponse.json({patterns:[],summary:{total:0,recurrence:0,reopened:0,evidence:0,ai:0,response:0}});
const {data,error}=await supabase.from("security_memory").select("id,memory_type,subject_id,title,summary,state,data,occurred_at").eq("organization_id",profile.organization_id).order("occurred_at",{ascending:false}).limit(300);
if(error)return NextResponse.json({error:error.message},{status:500});
const memories=(data??[]) as Memory[]; const patterns:Pattern[]=[];
const groups=new Map<string,Memory[]>();
for(const m of memories){const findingId=str(m.data.finding_id)??(m.memory_type==="finding_state"?m.subject_id:null); const assetId=str(m.data.asset_id)??str(m.data.affected_asset_id); const evidenceType=str(m.data.evidence_type); const indicator=str(m.data.indicator)??str(m.data.category); const key=findingId?"finding:"+findingId:assetId?"asset:"+assetId:evidenceType?"evidence:"+evidenceType:indicator?"indicator:"+indicator:null; if(!key)continue; const list=groups.get(key)??[]; list.push(m); groups.set(key,list);}
for(const [key,list] of groups){if(list.length<2)continue; const ordered=[...list].sort((a,b)=>new Date(a.occurred_at).getTime()-new Date(b.occurred_at).getTime()); const first=ordered[0],last=ordered[ordered.length-1],ids=ordered.slice(-8).map(x=>x.id);
if(key.startsWith("finding:"))patterns.push({id:"recurrence-"+key,pattern:"recurrence",title:"Recurring finding history detected",detail:"This finding has "+list.length+" recorded security-memory event(s) across time. Previous context should be reviewed before treating the latest observation as isolated.",confidence:"high",memoryIds:ids,firstObserved:first.occurred_at,lastObserved:last.occurred_at,boundary:"Recurrence is based on recorded memory, not proof that the condition is currently active."});
const hasResolution=ordered.some(m=>m.memory_type==="evidence_change"&&["resolved","cleared","healthy"].includes(str(m.data.current_security_state)??"")); const hasLaterActive=ordered.some((m,i)=>i>0&&["active","degraded","open"].includes(m.state));
if(hasResolution&&hasLaterActive)patterns.push({id:"reopened-"+key,pattern:"reopened_condition",title:"Condition appears to have returned after a recorded resolution",detail:"Historical memory contains a recorded cleared/resolved state followed by a later active/degraded/open state.",confidence:"high",memoryIds:ids,firstObserved:first.occurred_at,lastObserved:last.occurred_at,boundary:"This is a temporal pattern in recorded state transitions; current telemetry is required to establish present state."});
}
const evidenceGroups=new Map<string,Memory[]>();
for(const m of memories.filter(x=>x.memory_type==="evidence_change")){const key=(str(m.data.source)??"unknown")+":"+(str(m.data.title)??m.title)+":"+(str(m.data.asset_id)??"none"); const list=evidenceGroups.get(key)??[]; list.push(m); evidenceGroups.set(key,list);}
for(const [key,list] of evidenceGroups){if(list.length<3)continue; patterns.push({id:"evidence-repeat-"+key,pattern:"repeated_evidence_change",title:"Repeated evidence changes detected",detail:list.length+" recorded evidence transitions match the same source/title/asset context.",confidence:"medium",memoryIds:list.slice(0,8).map(x=>x.id),firstObserved:list[list.length-1].occurred_at,lastObserved:list[0].occurred_at,boundary:"Repeated change is an investigation signal, not proof of compromise."});}
const ai=memories.filter(m=>/(prompt injection|jailbreak|indirect prompt|credential|secret exposure|sensitive data|tool call|mcp|excessive permission|shadow ai)/i.test((m.title+" "+m.summary+" "+JSON.stringify(m.data)).toLowerCase())); const aiGroups=new Map<string,Memory[]>();
for(const m of ai){const category=str(m.data.category)??str(m.data.indicator)??"ai-security-signal"; const list=aiGroups.get(category)??[]; list.push(m); aiGroups.set(category,list);}
for(const [category,list] of aiGroups){if(list.length<2)continue; patterns.push({id:"ai-repeat-"+category,pattern:"repeated_ai_indicator",title:"Repeated AI security indicator: "+category,detail:list.length+" recorded memory event(s) contain the same AI-security indicator category.",confidence:"medium",memoryIds:list.slice(0,8).map(x=>x.id),firstObserved:list[list.length-1].occurred_at,lastObserved:list[0].occurred_at,boundary:"The indicator is evidence context only. It does not establish malicious behavior or compromise."});}
const decisions=memories.filter(m=>m.memory_type==="operator_decision"); const outcomes=memories.filter(m=>m.memory_type==="response_outcome");
if(decisions.length>0&&outcomes.length===0)patterns.push({id:"response-pending-outcome",pattern:"response_cycle",title:"Response decisions exist without recorded outcomes",detail:decisions.length+" operator decision memory event(s) exist, but no response outcome memory is currently recorded.",confidence:"medium",memoryIds:decisions.slice(0,8).map(x=>x.id),firstObserved:decisions.at(-1)?.occurred_at??new Date().toISOString(),lastObserved:decisions[0]?.occurred_at??new Date().toISOString(),boundary:"No outcome memory does not mean an action failed or succeeded; it means the outcome is not recorded."});
const unique=Array.from(new Map(patterns.map(p=>[p.id,p])).values()).sort((a,b)=>new Date(b.lastObserved).getTime()-new Date(a.lastObserved).getTime()).slice(0,25);
return NextResponse.json({patterns:unique,summary:{total:unique.length,recurrence:unique.filter(p=>p.pattern==="recurrence").length,reopened:unique.filter(p=>p.pattern==="reopened_condition").length,evidence:unique.filter(p=>p.pattern==="repeated_evidence_change").length,ai:unique.filter(p=>p.pattern==="repeated_ai_indicator").length,response:unique.filter(p=>p.pattern==="response_cycle").length},boundary:"Security Pattern Intelligence identifies deterministic patterns in recorded SentinelX memory. Patterns are investigation signals, not proof of compromise, attribution, or current security state."});
}catch{return NextResponse.json({error:"Security patterns could not be generated."},{status:500})}}